---
title: "mussel"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load data

```{r}
population=read.csv("data/population.csv")
str(population)
```

### Plot data

```{r}

# Calculate mean
mean= (population$R1+ population$R2+ population$R3)/3

A=5
# 1st quadrat
plot(mean/A,
     type='b', col='blue',
     xlab='', ylab='Population / m^2', xlim=c(1,12), xaxt='n', lwd=2)

#legend('top', legend=c('Mean'), col=c('blue'), lwd=c(3), lty=1)

grid()
axis(1, at=seq(1,12), population$Month, las=2, cex.axis = 1)
# title('Monthly variation in population density of L. marginalis')

```
```{r}
plot(population$R2,
     type='b', col='blue',
     xlab='', xlim=c(1,12), xaxt='n')
axis(1, at=seq(1,12), population$Month, las=2)

```

```{r}
plot(population$R3,
     type='b', col='blue',
     xlab='', xlim=c(1,12), xaxt='n')
axis(1, at=seq(1,12), population$Month, las=2)

```
### Water quality

```{r}
water=read.csv("data/water-quality.csv")
str(water)

plot(water$Depth, mean/A,
     type='p', col='blue',
     xlab='Depth (m)', ylab='Population / m^2')

plot(water$Temperature, mean/A,
     type='p', col='blue',
     xlab='Temperature °C', ylab='Population / m^2')

plot(water$pH, mean/A,
     type='p', col='blue',
     xlab='pH', ylab='Population / m^2')
```




### Temperature

```{r}
library(ggplot2)

# Month needs to be factorized to facilitate plotting and preserve order
Month1=factor(water$Month, levels=water$Month)
df= data.frame(Month=Month1, Depth=water$Depth,
               Temperature=water$Temperature, pH=water$pH, mean=mean/A)


scale=6

ggplot(data = df, aes(x = Month, group = 1)) +
  geom_line(aes(y = mean, color = "black"), linewidth = 1.3) +
  geom_point(aes(y = mean, color = "black"), shape=1, size=3) +
  
  geom_line(aes(y = Temperature / scale, color = "blue"), linewidth = 1.3) +
  geom_point(aes(y = Temperature / scale, color = "blue"), shape=1, size=3) +

  scale_y_continuous(name = "Population / m^2",
                     sec.axis = sec_axis(transform = ~ . * scale, name = "Temperature °C")) +
  scale_color_manual('', labels= c('Population / m^2','Temperature °C'),
                     values = c("black", "blue")) +
  theme_bw() +
  theme(legend.position = "top", axis.text.x= element_text(size=11, angle = 90, vjust = 0.5),
        axis.text.y.right= element_text(size=11, color='blue'),
        axis.title.y.right = element_text(color='blue'))


```


### Depth

```{r}
scale=1
ggplot(data = df, aes(x = Month, group = 1)) +
  geom_line(aes(y = mean, color = "black"), linewidth = 1.3) +
  geom_point(aes(y = mean, color = "black"), shape=1, size=3) +
  
  geom_line(aes(y = Depth / scale, color = "blue"), linewidth = 1.3) +
  geom_point(aes(y = Depth / scale, color = "blue"), shape=1, size=3) +

  scale_y_continuous(name = "Population / m^2",
                     sec.axis = sec_axis(transform = ~ . * scale, name = "Depth")) +
  scale_color_manual('', labels= c('Population / m^2','Depth'),
                     values = c("black", "blue")) +
  theme_bw() +
  theme(legend.position = "top", axis.text.x= element_text(size=11, angle = 90, vjust = 0.5),
        axis.text.y.right= element_text(size=11, color='blue'),
        axis.title.y.right = element_text(color='blue'))

```


### pH

```{r}
scale=2
ggplot(data = df, aes(x = Month, group = 1)) +
  geom_line(aes(y = mean, color = "black"), linewidth = 1.3) +
  geom_point(aes(y = mean, color = "black"), shape=1, size=3) +
  
  geom_line(aes(y = pH / scale, color = "blue"), linewidth = 1.3) +
  geom_point(aes(y = pH / scale, color = "blue"), shape=1, size=3) +

  scale_y_continuous(name = "Population / m^2",
                     sec.axis = sec_axis(transform = ~ . * scale, name = "pH")) +
  scale_color_manual('', labels= c('Population / m^2','pH'),
                     values = c("black", "blue")) +
  theme_bw() +
  theme(legend.position = "top", axis.text.x= element_text(size=11, angle = 90, vjust = 0.5),
        axis.text.y.right= element_text(size=11, color='blue'),
        axis.title.y.right = element_text(color='blue'))

```



### Correlation

Reference: https://www.sthda.com/english/wiki/correlation-test-between-two-variables-in-r#compute-correlation-in-r


```{r}
for (i in colnames(df)[2:4]) {
  print(i)
  print(cor.test(df[[i]], mean, method='spearman'))
  cat(sprintf('\n'))
}

```


### Visualize correlation

```{r}
library("ggpubr")
ggscatter(df, x = "Depth", y = "mean",
          add = "reg.line", conf.int = TRUE,
          cor.coef = FALSE, cor.method = "spearman",
          xlab = "Depth (m)", ylab = "Population / m^2",
          title = 'A') +
  stat_cor(cor.coef.name = 'rho', label.x=1.6, label.y=2.6)
```

```{r}
library("ggpubr")
ggscatter(df, x = "Temperature", y = "mean",
          add = "reg.line", conf.int = TRUE,
          cor.coef = TRUE, cor.method = "spearman",
          xlab ="Temperature (C)", ylab = "Population / m^2")
```

```{r}
library("ggpubr")
ggscatter(df, x = "pH", y = "mean",
          add = "reg.line", conf.int = TRUE,
          cor.coef = TRUE, cor.method = "spearman",
          xlab = "pH", ylab = "Population / m^2")
```
 
### Load data
 
```{r}
bio= read.csv('data/shell-biometrics.csv')
str(bio)
``` 
 
### Normality test
 
<!-- #### Length -->
<!-- ```{r} -->
<!-- shapiro.test(bio$Shell_Length_mm) -->
<!-- ggqqplot(bio$Shell_Width_mm, ylab = "Length") -->
<!-- ``` -->
<!-- ###Height -->
<!-- ```{r} -->
<!-- shapiro.test(bio$Shell_Height_mm) -->
<!-- ggqqplot(bio$Shell_Width_mm, ylab = "Height") -->
<!-- ``` -->
<!-- ###Width -->
<!-- ```{r} -->
<!-- shapiro.test(bio$Shell_Width_mm) -->
<!-- ggqqplot(bio$Shell_Width_mm, ylab = "Width") -->
<!-- ``` -->

```{r}
mean(water$Temperature)
```
```{r}
sd(water$Temperature)
```
```{r}
mean(water$pH)
```
```{r}
sd(water$pH)
```
```{r}
mean(water$Depth)
```
```{r}
sd(water$Depth)
```
### Analyze quadrat samples using Mann-Whitney U test

```{r}
wilcox.test(population$R1, population$R2)
```

```{r}
wilcox.test(population$R2, population$R3)
```

```{r}
wilcox.test(population$R3, population$R1)
```
```{r}
for (w in c('Depth','Temperature','pH')) {
  arr=water[[w]]
  cat(sprintf('%s - Mean: %f, min: %f, max: %f\n', w, mean(arr), min(arr), max(arr)))
}
```

### End
